# Site settings
baseurl = "http://navneetchouhan.com/"
languageCode = "en-us"
title = "Navneet Chauhan"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Navneet Kaur"
    description = "Hello from designer"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "navneet.chouhan88@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Navneet Kaur"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Navneet Kaur"
        subtitle = "Designer - Passionate - Awesome"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Hi, I'm Navneet. I build websites front end, logos, icons and digital products. Design to me is a way of life. It's not a job but a passion that you grow with every day. I've been a self-taught designer and currently I am enrolled in Web and Mobile App Designing at Langara College, Vancouver"
        right = "I start the design with a pencil and paper,thinking about the problem and the solution. I’ll then sit down at my computer and start with wire frames and low level mockups. Then add the imagery, typography design and details. I use Photoshop and Illustrator for my layout and design."

        [params.about.button]
            text = "Download Resume"
            link = "http://mylinux.langara.bc.ca/~nchauhan00/resume/"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "© 2017 Website designed by [Navneet Kaur](//navneetchouhan.com)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Vancouver, BC", "Canada"]

        [params.footer.social]
            title = "Find Me On"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "https://github.com/navneetchouhan/"

            [[params.footer.social.networks]]
                icon = "fa-google-plus"
                link=  "https://plus.google.com/111782134545195266610"


        [params.footer.credits]
            title = "Quick Contact"
            text = "navneet.chouhan88@gmail.com"
